ARG FROM_IMAGE=osrf/ros:jazzy-desktop-full
FROM ${FROM_IMAGE}

SHELL ["/bin/bash", "-c"]

ARG OVERLAY_WS=/opt/ros/overlay_ws
ENV OVERLAY_WS=${OVERLAY_WS}
ENV CRAM_VENV=/opt/ros/cram-env

ENV UV_PROJECT_ENVIRONMENT=${CRAM_VENV}
ENV DEBIAN_FRONTEND=noninteractive


ARG INDEX_URL=https://pypi.org/simple
ENV PIP_INDEX_URL=${INDEX_URL}
ENV UV_DEFAULT_INDEX=${INDEX_URL}


WORKDIR /opt/ros
COPY .github/docker/setup_ros_workspace.sh /tmp/setup_ros_workspace.sh
COPY .github/docker/setup_workspace.py     /tmp/setup_workspace.py
RUN apt-get update \
    && apt-get install -y --no-install-recommends ros-jazzy-ur-client-library \
    && sed -i 's#colcon build --merge-install#colcon build --merge-install --packages-ignore iai_daisy_description#' /tmp/setup_workspace.py \
    && OVERLAY_WS=${OVERLAY_WS} bash /tmp/setup_ros_workspace.sh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


RUN source /opt/ros/jazzy/setup.bash \
    && python3 -m venv "${CRAM_VENV}" --system-site-packages \
    && source "${CRAM_VENV}/bin/activate" \
    && pip install --no-cache-dir uv


WORKDIR /root/cognitive_robot_abstract_machine
COPY . .
RUN source /opt/ros/jazzy/setup.bash \
    && source "${OVERLAY_WS}/install/setup.bash" \
    && source "${CRAM_VENV}/bin/activate" \
    && uv sync --extra dev --active


RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        xvfb libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
        libxcb-render-util0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0 libegl1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN source "${CRAM_VENV}/bin/activate" \
    && uv pip install PyQt6 qtconsole


COPY .github/docker/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["bash", "/entrypoint.sh"]
CMD ["bash"]
